-- MySQL Script generated by MySQL Workbench
-- Wed Apr 24 20:52:15 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fueldb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fueldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fueldb` DEFAULT CHARACTER SET utf8 ;
USE `fueldb` ;

-- -----------------------------------------------------
-- Table `fueldb`.`Driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fueldb`.`Driver` (
  `driver_id` INT NOT NULL AUTO_INCREMENT,
  `Surname` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Middle_name` VARCHAR(45) NOT NULL,
  `Phone_number` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`driver_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fueldb`.`Fuel tanker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fueldb`.`Fuel tanker` (
  `Fuel_tanker_id` INT NOT NULL AUTO_INCREMENT,
  `Model` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Fuel_tanker_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fueldb`.`Fuel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fueldb`.`Fuel` (
  `Fuel_id` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Fuel_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fueldb`.`Gas station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fueldb`.`Gas station` (
  `Gas_station_id` INT NOT NULL AUTO_INCREMENT,
  `Address` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Gas_station_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fueldb`.`Fuel container`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fueldb`.`Fuel container` (
  `Fuel_container_id` INT NOT NULL AUTO_INCREMENT,
  `Capacity` DECIMAL(7,2) NOT NULL,
  `Fuel_amount` DECIMAL(7,2) NOT NULL,
  `Gas_station_id` INT NOT NULL,
  `Fuel_id` INT NOT NULL,
  PRIMARY KEY (`Fuel_container_id`),
  INDEX `Gas_station_id2_idx` (`Gas_station_id` ASC) VISIBLE,
  INDEX `Fuel_id2_idx` (`Fuel_id` ASC) VISIBLE,
  CONSTRAINT `Gas_station_id2`
    FOREIGN KEY (`Gas_station_id`)
    REFERENCES `fueldb`.`Gas station` (`Gas_station_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Fuel_id2`
    FOREIGN KEY (`Fuel_id`)
    REFERENCES `fueldb`.`Fuel` (`Fuel_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fueldb`.`Technical Specialist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fueldb`.`Technical Specialist` (
  `Technical_Specialist_id` INT NOT NULL AUTO_INCREMENT,
  `Surname` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Middle_name` VARCHAR(45) NOT NULL,
  `Phone_number` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Technical_Specialist_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fueldb`.`Driver-Fuel tanker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fueldb`.`Driver-Fuel tanker` (
  `Driver-Fuel_tanker_id` INT NOT NULL AUTO_INCREMENT,
  `Driver_id` INT NOT NULL,
  `Fuel_tanker_id` INT NOT NULL,
  PRIMARY KEY (`Driver-Fuel_tanker_id`, `Driver_id`),
  INDEX `driver_id1_idx` (`Driver_id` ASC) VISIBLE,
  INDEX `fuel_tanker_id1_idx` (`Fuel_tanker_id` ASC) VISIBLE,
  CONSTRAINT `driver_id1`
    FOREIGN KEY (`Driver_id`)
    REFERENCES `fueldb`.`Driver` (`driver_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fuel_tanker_id1`
    FOREIGN KEY (`Fuel_tanker_id`)
    REFERENCES `fueldb`.`Fuel tanker` (`Fuel_tanker_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fueldb`.`Fuel tanker-Fuel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fueldb`.`Fuel tanker-Fuel` (
  `Fuel_tanker-Fuel_id` INT NOT NULL AUTO_INCREMENT,
  `Fuel_id` INT NOT NULL,
  `Fuel_tanker_id` INT NOT NULL,
  `Capacity` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`Fuel_tanker-Fuel_id`),
  INDEX `Fuel_tanker_id2_idx` (`Fuel_tanker_id` ASC) VISIBLE,
  INDEX `Fuel_id_idx` (`Fuel_id` ASC) VISIBLE,
  CONSTRAINT `Fuel_tanker_id2`
    FOREIGN KEY (`Fuel_tanker_id`)
    REFERENCES `fueldb`.`Fuel tanker` (`Fuel_tanker_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Fuel_id`
    FOREIGN KEY (`Fuel_id`)
    REFERENCES `fueldb`.`Fuel` (`Fuel_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fueldb`.`Technical Specialist-Fuel tanker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fueldb`.`Technical Specialist-Fuel tanker` (
  `Technical_Specialist-Fuel_tanker_id` INT NOT NULL AUTO_INCREMENT,
  `Technical_Specialist_id` INT NOT NULL,
  `Fuel_tanker_id` INT NOT NULL,
  PRIMARY KEY (`Technical_Specialist-Fuel_tanker_id`),
  INDEX `Fuel_tanker_id2_idx` (`Fuel_tanker_id` ASC) VISIBLE,
  INDEX `Technical_Specialist_id_idx` (`Technical_Specialist_id` ASC) VISIBLE,
  CONSTRAINT `Fuel_tanker_id3`
    FOREIGN KEY (`Fuel_tanker_id`)
    REFERENCES `fueldb`.`Fuel tanker` (`Fuel_tanker_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Technical_Specialist_id`
    FOREIGN KEY (`Technical_Specialist_id`)
    REFERENCES `fueldb`.`Technical Specialist` (`Technical_Specialist_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fueldb`.`Technical Specialist-Fuel containers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fueldb`.`Technical Specialist-Fuel containers` (
  `Technical_Specialist-Fuel_containers_id` INT NOT NULL AUTO_INCREMENT,
  `Technical_Specialist_id` INT NOT NULL,
  `Fuel_containers_id` INT NOT NULL,
  PRIMARY KEY (`Technical_Specialist-Fuel_containers_id`),
  INDEX `Technical_Specialist_id2_idx` (`Technical_Specialist_id` ASC) VISIBLE,
  INDEX `Fuel_containers_id_idx` (`Fuel_containers_id` ASC) VISIBLE,
  CONSTRAINT `Technical_Specialist_id2`
    FOREIGN KEY (`Technical_Specialist_id`)
    REFERENCES `fueldb`.`Technical Specialist` (`Technical_Specialist_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Fuel_containers_id`
    FOREIGN KEY (`Fuel_containers_id`)
    REFERENCES `fueldb`.`Fuel container` (`Fuel_container_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fueldb`.`Fuel tanker-Gas station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fueldb`.`Fuel tanker-Gas station` (
  `Fuel_tanker-Gas_station_id` INT NOT NULL AUTO_INCREMENT,
  `Fuel_tanker-Fuel_id` INT NOT NULL,
  `Gas_station_id` INT NOT NULL,
  `Visit_date` DATE NOT NULL,
  `Quantity` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`Fuel_tanker-Gas_station_id`),
  INDEX `Fuel_tanker-Fuel_id_idx` (`Fuel_tanker-Fuel_id` ASC) VISIBLE,
  INDEX `Gas_station_id_idx` (`Gas_station_id` ASC) VISIBLE,
  CONSTRAINT `Fuel_tanker-Fuel_id`
    FOREIGN KEY (`Fuel_tanker-Fuel_id`)
    REFERENCES `fueldb`.`Fuel tanker-Fuel` (`Fuel_tanker-Fuel_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Gas_station_id`
    FOREIGN KEY (`Gas_station_id`)
    REFERENCES `fueldb`.`Gas station` (`Gas_station_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
